version: '3.4'

services:
  
  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
        NAME: "rabbitmq"
    ports:
        - "4369:4369"
        - "5671:5671"
        - "5672:5672"
        - "25672:25672"
        - "15671:15671"
        - "15672:15672"
    restart: always

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Your_password123"
        ACCEPT_EULA: "Y"
    healthcheck:
        test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-U", "sa", "-P", "Your_password123", "-Q", "select 1" ]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 90s
    restart: always

  rapitest:
    image: alexandrerocha99/rapitest:3.1
    depends_on:
        db:
            condition: service_healthy
        rabbitmq:
            condition: service_started
    ports:
        - "8080:80"
    restart: always

  runtestsworkerservice:
    image: alexandrerocha99/runtestsworkerservice:3.0
    depends_on:
        db:
            condition: service_healthy
        rabbitmq:
            condition: service_started
    restart: always


  setuptestsworkerservice:
    image: alexandrerocha99/setuptestsworkerservice:3.0
    depends_on:
        db:
            condition: service_healthy
        rabbitmq:
            condition: service_started
    restart: always